// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAGqQb1rcYAEDrfYWHoNjLkj5OFcfRpTo',
    appId: '1:6670229919:web:69841e2acc72141c481daa',
    messagingSenderId: '6670229919',
    projectId: 'neuroinsight-784ee',
    authDomain: 'neuroinsight-784ee.firebaseapp.com',
    storageBucket: 'neuroinsight-784ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfmIkO0iN2unL83oqBCXVacRK-pGUXXI',
    appId: '1:6670229919:android:ffc2830fe992d360481daa',
    messagingSenderId: '6670229919',
    projectId: 'neuroinsight-784ee',
    storageBucket: 'neuroinsight-784ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeAPhXNatbtyCpRg82y5QA6zXrYPpAEmo',
    appId: '1:6670229919:ios:3a1fda9aa055f344481daa',
    messagingSenderId: '6670229919',
    projectId: 'neuroinsight-784ee',
    storageBucket: 'neuroinsight-784ee.firebasestorage.app',
    iosBundleId: 'com.example.neuroinsightPdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeAPhXNatbtyCpRg82y5QA6zXrYPpAEmo',
    appId: '1:6670229919:ios:3a1fda9aa055f344481daa',
    messagingSenderId: '6670229919',
    projectId: 'neuroinsight-784ee',
    storageBucket: 'neuroinsight-784ee.firebasestorage.app',
    iosBundleId: 'com.example.neuroinsightPdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAGqQb1rcYAEDrfYWHoNjLkj5OFcfRpTo',
    appId: '1:6670229919:web:c4251512ce734a3f481daa',
    messagingSenderId: '6670229919',
    projectId: 'neuroinsight-784ee',
    authDomain: 'neuroinsight-784ee.firebaseapp.com',
    storageBucket: 'neuroinsight-784ee.firebasestorage.app',
  );
}
